deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Configure kubectl with Minikube kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config
        kubectl cluster-info

    - name: Deploy to Minikube
      run: |
        kubectl create deployment my-node-app --image=masadkh/my-node-app:latest || \
        kubectl set image deployment/my-node-app my-node-app=masadkh/my-node-app:latest
        kubectl expose deployment my-node-app --type=NodePort --port=3000 || true
